# Generated by Django 4.2.14 on 2024-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="rating_max_min",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_max_min",
            ),
        ),
    ]
